<a href="https://colab.research.google.com/github/AshvinVignesh/Sentiment-Analysis/blob/master/model/Emoji_with_their_meaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install demoji

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting demoji
  Downloading demoji-1.1.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.9/42.9 KB 4.4 MB/s eta 0:00:00
Installing collected packages: demoji
Successfully installed demoji-1.1.0

In [ ]:
import pandas as pd
import re
import string

In [ ]:
joy = ['\U0001F600', '\U0001F602', '\U0001F603', '\U0001F604',
          '\U0001F606', '\U0001F607', '\U0001F609', '\U0001F60A',
          '\U0001F60B', '\U0001F60C', '\U0001F60D', '\U0001F60E',
          '\U0001F60F', '\U0001F31E', '\U0000263A', '\U0001F618',
          '\U0001F61C', '\U0001F61D', '\U0001F61B', '\U0001F63A',
          '\U0001F638', '\U0001F639', '\U0001F63B', '\U0001F63C',
          '\U00002764', '\U0001F496', '\U0001F495', '\U0001F601',
          '\U00002665', ]#joy

anger = ['\U0001F62C', '\U0001F620', '\U0001F610',
          '\U0001F611', '\U0001F620', '\U0001F621', '\U0001F616',
          '\U0001F624', '\U0001F63E']#anger
disgust= ['\U0001F4A9']#disgust
fear = ['\U0001F605', '\U0001F626', '\U0001F627', '\U0001F631',
          '\U0001F628', '\U0001F630', '\U0001F640']#fear
sad = ['\U0001F614', '\U0001F615', '\U00002639', '\U0001F62B',
          '\U0001F629', '\U0001F622', '\U0001F625', '\U0001F62A',
          '\U0001F613', '\U0001F62D', '\U0001F63F', '\U0001F494']#sad
surp = ['\U0001F633', '\U0001F62F', '\U0001F635', '\U0001F632']#surprise

emojilist = {'joy':joy, 'anger':anger, 'disgust':disgust, 'fear':fear, 'sad':sad, 'surprise':surp}
for i in emojilist:
    print('There are {} emoji contains in the cluster {}'.format(len(emojilist[i]), i))
    print(i,emojilist[i])

There are 29 emoji contains in the cluster joy
joy ['😀', '😂', '😃', '😄', '😆', '😇', '😉', '😊', '😋', '😌', '😍', '😎', '😏', '🌞', '☺', '😘', '😜', '😝', '😛', '😺', '😸', '😹', '😻', '😼', '❤', '💖', '💕', '😁', '♥']
There are 9 emoji contains in the cluster anger
anger ['😬', '😠', '😐', '😑', '😠', '😡', '😖', '😤', '😾']
There are 1 emoji contains in the cluster disgust
disgust ['💩']
There are 7 emoji contains in the cluster fear
fear ['😅', '😦', '😧', '😱', '😨', '😰', '🙀']
There are 12 emoji contains in the cluster sad
sad ['😔', '😕', '☹', '😫', '😩', '😢', '😥', '😪', '😓', '😭', '😿', '💔']
There are 4 emoji contains in the cluster surprise
surprise ['😳', '😯', '😵', '😲']

In [ ]:
data={'emoji':['😀', '😂', '😃', '😄', '😆', '😇', '😉', '😊', '😋', '😌', '😍', '😎', '😏', '🌞', '☺', '😘', '😜', '😝', '😛', '😺', '😸', '😹', '😻', '😼', '❤', '💖', '💕', '😁', '♥','😬', '😠', '😐', '😑', '😠', '😡', '😖', '😤', '😾','💩','😅', '😦', '😧', '😱', '😨', '😰', '🙀','😔', '😕', '☹', '😫', '😩', '😢', '😥', '😪', '😓', '😭', '😿', '💔','😳', '😯', '😵', '😲'],
      }

In [ ]:
df=pd.DataFrame(data)

df

   emoji
0      😀
1      😂
2      😃
3      😄
4      😆
..   ...
57     💔
58     😳
59     😯
60     😵
61     😲

[62 rows x 1 columns]

In [ ]:
df.to_csv('emoji_meeaning.txt')

In [ ]:
DF = pd.read_csv('emoji_meeaning.txt')

In [ ]:
import demoji
demoji.download_codes()
def get_emoji_meaning(e):
    return demoji.replace_with_desc(e)

<ipython-input-8-7da691562c49>:2: FutureWarning: The demoji.download_codes attribute is deprecated and will be removed from demoji in a future version. It is an unused attribute as emoji codes are now distributed directly with the demoji package.
  demoji.download_codes()

In [ ]:
DF['meaning'] = DF['emoji'].apply(lambda x: ''.join(get_emoji_meaning(e) for e in x))

In [ ]:
DF.head(10)

   Unnamed: 0 emoji                            meaning
0           0     😀                    :grinning face:
1           1     😂           :face with tears of joy:
2           2     😃      :grinning face with big eyes:
3           3     😄  :grinning face with smiling eyes:
4           4     😆          :grinning squinting face:
5           5     😇           :smiling face with halo:
6           6     😉                     :winking face:
7           7     😊   :smiling face with smiling eyes:
8           8     😋               :face savoring food:
9           9     😌                    :relieved face:

In [ ]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [ ]:
DF['meaning'] =  DF['meaning'].apply(remove_punctuation)

In [ ]:
DF.head(10)

   Unnamed: 0 emoji                          meaning
0           0     😀                    grinning face
1           1     😂           face with tears of joy
2           2     😃      grinning face with big eyes
3           3     😄  grinning face with smiling eyes
4           4     😆          grinning squinting face
5           5     😇           smiling face with halo
6           6     😉                     winking face
7           7     😊   smiling face with smiling eyes
8           8     😋               face savoring food
9           9     😌                    relieved face

In [ ]:
import nltk
from nltk.stem import PorterStemmer

# download necessary nltk resources (only needed once)
nltk.download('punkt')

# create a stemmer object
stemmer = PorterStemmer()

# define a DataFrame with text data
data = pd.DataFrame({'text': ['I am running in the park and seeing a lot of runners',
                              'She is walking her dog in the neighborhood']})

# apply tokenization and stemming to the text column of the DataFrame
data['tokens'] = data['text'].apply(nltk.word_tokenize)
data['stemmed_tokens'] = data['tokens'].apply(lambda x: [stemmer.stem(word) for word in x])

# join the stemmed tokens back into a sentence without commas
data['stemmed_text'] = data['stemmed_tokens'].apply(lambda x: " ".join(x))

# print the original text and the stemmed text
print("Original DataFrame:\n", data[['text']])
print("Stemmed DataFrame:\n", data[['stemmed_text']])

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

Original DataFrame:
                                                 text
0  I am running in the park and seeing a lot of r...
1         She is walking her dog in the neighborhood
Stemmed DataFrame:
                                    stemmed_text
0  i am run in the park and see a lot of runner
1       she is walk her dog in the neighborhood

In [ ]:
DF['meaning'] =  DF['meaning'].apply(nltk.word_tokenize)

In [ ]:
DF['meaning'] =  DF['meaning'].apply(lambda x: [stemmer.stem(word) for word in x])

In [ ]:
DF['meaning'] =  DF['meaning'].apply(lambda x: " ".join(x))

In [ ]:
DF.head(10)

   Unnamed: 0 emoji                    meaning
0           0     😀                  grin face
1           1     😂      face with tear of joy
2           2     😃     grin face with big eye
3           3     😄   grin face with smile eye
4           4     😆           grin squint face
5           5     😇       smile face with halo
6           6     😉                  wink face
7           7     😊  smile face with smile eye
8           8     😋            face savor food
9           9     😌                reliev face

In [ ]:
counts =DF['meaning'].value_counts()

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
print(counts)

angri face                    2
neutral face                  1
pout face                     1
confound face                 1
face with steam from nose     1
pout cat                      1
pile of poo                   1
grin face with sweat          1
frown face with open mouth    1
anguish face                  1
face scream in fear           1
fear face                     1
anxiou face with sweat        1
weari cat                     1
pensiv face                   1
confus face                   1
frown face                    1
tire face                     1
weari face                    1
cri face                      1
sad but reliev face           1
sleepi face                   1
downcast face with sweat      1
loudli cri face               1
cri cat                       1
broken heart                  1
flush face                    1
hush face                     1
knockedout face               1
expressionless face           1
grin face                     1
face with tear of joy         1
grimac face                   1
grin face with big eye        1
grin face with smile eye      1
grin squint face              1
smile face with halo          1
wink face                     1
smile face with smile eye     1
face savor food               1
reliev face                   1
smile face with heartey       1
smile face with sunglass      1
smirk face                    1
sun with face                 1
smile face                    1
face blow a kiss              1
wink face with tongu          1
squint face with tongu        1
face with tongu               1
grin cat                      1
grin cat with smile eye       1
cat with tear of joy          1
smile cat with heartey        1
cat with wri smile            1
red heart                     1
sparkl heart                  1
two heart                     1
beam face with smile eye      1
heart suit                    1
astonish face                 1
Name: meaning, dtype: int64

In [ ]:
DF.to_csv('ConvertToSinhala.csv')

In [ ]:
# english-sinhala dictionary
dictionary = {}
df= pd.read_csv('download.csv')
dictionary_file = df["En,sinhala"]

for line in dictionary_file:
    key, value = line.strip().split(",")
    dictionary[key] = value

In [ ]:
# to check whether the string contains English words(any)
def translate_english(x):
    for word1 in x.split():
        new_word = ''.join(i for i in word1 if not i.isdigit())
        x = x.replace(word1, new_word)
    for word in x.split():
        word2 = "".join(l for l in word if l not in string.punctuation)
        if re.match('[a-zA-Z]', word2) is not None:
            word1 = word2.lower()
            translated_word = dictionary.get(word1)
            if translated_word is None:
                translated_word = ''
            x = x.replace(word, translated_word)
    return x

In [ ]:
DF['meaning'] = DF['meaning'].apply(translate_english)

In [ ]:
DF = DF.drop(['Unnamed: 0'],axis=1)

In [ ]:
DF.head(10)

  emoji                    meaning
0     😀                සිනහව මුහුණ
1     😂    මුහුණ සමග ඉරීම  වල සතුට
2     😃     සිනහව මුහුණ සමග මහා ඇස
3     😄   සිනහව මුහුණ සමග සිනහව ඇස
4     😆  සිනහව ඇස් දිලිසෙනවා මුහුණ
5     😇        සිනහව මුහුණ සමග හලෝ
6     😉        ඇසිපිය හෙළන්න මුහුණ
7     😊   සිනහව මුහුණ සමග සිනහව ඇස
8     😋      මුහුණ රස විඳින්න ආහාර
9     😌                 සහනය මුහුණ

In [ ]:
import pandas as pd

# create a sample DataFrame with two columns
df = pd.DataFrame({'col1': ['Hello', 'How', 'Are', 'You'], 
                   'col2': ['World', 'Are', 'You', 'Doing']})

# concatenate the two columns and store the result in a new column
df['merged_col'] = df['col1'] + ' ' + df['col2']

# print the result
print(df)

    col1   col2   merged_col
0  Hello  World  Hello World
1    How    Are      How Are
2    Are    You      Are You
3    You  Doing    You Doing